name: "godot-ci export"
on:
  push:
    branches:
      - main

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: cshark-at-sea-server
  PROJECT_PATH: godot

jobs:
   export-linux-server:
    name: Linux Export
    runs-on: ubuntu-22.04  # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "linux-server" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
          
      - name: 'Login to GitHub Container Registry'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-
              
      - name: Build Docker image
        run: docker build -f ./docker/server.Dockerfile -t ghcr.io/${{ github.repository }}/$EXPORT_NAME:latest .
        
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/$EXPORT_NAME:latest
        
 
